Repository SFML/SFML, pull requests merged in 2018-12, with the labels that each got.

#1519 Fixed example documentation to match the code
  include/SFML/Audio/SoundStream.hpp
Labels: bug, m:doc, s:accepted

#1526 Use travis for windows builds
  .travis.yml
  appveyor.yml
Labels: feature, m:config, s:accepted

#1522 iOS example updates
  cmake/Macros.cmake
  examples/assets/Info.plist
  examples/assets/Launch Screen.storyboard
  examples/assets/icon.icns
  examples/assets/logo.png
  examples/iOS/resources/canary.wav
  examples/iOS/resources/image.png
  examples/iOS/resources/orchestral.ogg
  examples/iOS/resources/sansation.ttf
  examples/opengl/OpenGL.cpp
  examples/pong/Pong.cpp
  examples/window/Window.cpp
Labels: feature, m:config, p:ios, s:accepted
