Repository SFML/SFML, pull requests merged in 2020-11, with the labels that each got.

#1716 Add Github Actions.
  .github/workflows/ci.yml
Labels: feature, m:config, s:accepted

#1720 Add apt-get update command for the CI
  .github/workflows/ci.yml
Labels: bug, m:config, p:linux, s:accepted

#1688 Added support for directional arrow resize cursors on Linux
  include/SFML/Window/Cursor.hpp
  src/SFML/Window/OSX/CursorImpl.mm
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Win32/CursorImpl.cpp
Labels: feature, m:sfml-window, s:accepted
