Repository SFML/SFML, pull requests merged in 2022-05, with the labels that each got.

#2088 Add clarification of SFML's status of development
  readme.md
Labels: feature, s:accepted, m:doc

#2081 Add tests for `sf::err`
  test/CMakeLists.txt
  test/System/Err.cpp
Labels: feature, s:accepted, m:unittest

#2089 Remove unnecessary lossy conversions in test utilities
  test/System/Vector2.cpp
  test/TestUtilities/SystemUtil.hpp
Labels: bug, s:accepted, m:unittest

#2090 try_emplace in Font::loadPage
  src/SFML/Graphics/Font.cpp
Labels: feature, m:sfml-graphics, s:accepted

#2091 replacing `NULL` with `nullptr` in src/window files
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/DRMContext.hpp
  src/SFML/Window/DRM/InputImplUDev.cpp
  src/SFML/Window/Unix/Display.cpp
Labels: feature, m:sfml-window, s:accepted, p:linux

#2094 Fix incorrect cast when loading 16-bit samples from WAV file
  src/SFML/Audio/SoundFileReaderWav.cpp
Labels: bug, m:sfml-audio, s:accepted

#2092 Apply compiler warnings to test utilities
  test/CMakeLists.txt
  test/TestUtilities/SystemUtil.cpp
Labels: bug, s:accepted, m:unittest

#2093 Remove MSVC compiler warnings override
  CMakeLists.txt
  cmake/CompilerOptionsOverride.cmake
Labels: feature, s:accepted, m:config

#2099 Backmerge 2.6.x to master
  include/SFML/Audio/Music.hpp
  src/SFML/Audio/SoundFileReaderWav.cpp
Labels: feature, s:accepted

#2086 Add extension methods to `Vector3<T>`
  include/SFML/System/Vector2.hpp
  include/SFML/System/Vector3.hpp
  include/SFML/System/Vector3.inl
  test/System/Vector2.cpp
  test/System/Vector3.cpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
Labels: feature, m:sfml-system, s:accepted

#2102 Fix conversion warning
  test/TestUtilities/SystemUtil.cpp
Labels: bug, s:accepted

#2103 Simplify approximate comparisons of SFML types
  test/Graphics/CircleShape.cpp
  test/Graphics/Shape.cpp
  test/Graphics/Transform.cpp
  test/Graphics/Transformable.cpp
  test/System/Angle.cpp
  test/System/Time.cpp
  test/System/Vector2.cpp
  test/System/Vector3.cpp
  test/TestUtilities/GraphicsUtil.cpp
  test/TestUtilities/GraphicsUtil.hpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
Labels: feature, s:accepted, m:unittest
