Repository SFML/SFML, pull requests merged in 2022-01, with the labels that each got.

#1928 Stop configuration when GCC is detected on macOS
  cmake/Macros.cmake
Labels: feature, p:macos, s:accepted, m:config

#1932 Add move semantics to 'System' module
  include/SFML/System/FileInputStream.hpp
  include/SFML/System/SuspendAwareClock.hpp
  src/SFML/System/FileInputStream.cpp
  src/SFML/System/Lock.cpp
  test/CMakeLists.txt
  test/System/FileInputStream.cpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
Labels: feature, m:sfml-system, s:accepted, m:unittest

#1944 Remove redundant doctest formatters
  test/System/Time.cpp
  test/Window/VideoMode.cpp
Labels: feature, s:accepted, m:unittest

#1953 Fix constructor typo in Unix/X11
  src/SFML/Window/Unix/WindowImplX11.cpp
Labels: bug, m:sfml-window, s:accepted, p:linux

#1949 Only build Cocoa example when using Xcode
  examples/CMakeLists.txt
Labels: bug, p:macos, s:accepted, m:config

#1956 Add tests for sf::Vertex
  test/CMakeLists.txt
  test/Graphics/Vertex.cpp
Labels: feature, s:accepted, m:unittest

#1948 Remove redundant 4-param sf::Rect<T> constructor
  examples/shader/Shader.cpp
  include/SFML/Graphics/Image.hpp
  include/SFML/Graphics/Rect.hpp
  include/SFML/Graphics/Rect.inl
  src/SFML/Graphics/Font.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/Shape.cpp
  src/SFML/Graphics/Sprite.cpp
  src/SFML/Graphics/Transform.cpp
  src/SFML/Graphics/VertexArray.cpp
  src/SFML/Graphics/View.cpp
  test/Graphics/Rect.cpp
Labels: feature, m:sfml-graphics, s:accepted

#1957 Define fixed-width integer type aliases in terms of standard fixed-width types
  include/SFML/Config.hpp
Labels: feature, s:accepted, m:config

#1959 Use operator<< for printing during test failure
  test/Graphics/Color.cpp
  test/Graphics/Rect.cpp
  test/Graphics/Vertex.cpp
  test/System/FileInputStream.cpp
  test/System/Time.cpp
  test/System/Vector2.cpp
  test/System/Vector3.cpp
  test/TestUtilities/GraphicsUtil.cpp
  test/TestUtilities/GraphicsUtil.hpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
  test/TestUtilities/WindowUtil.cpp
  test/TestUtilities/WindowUtil.hpp
  test/Window/VideoMode.cpp
Labels: feature, s:accepted, m:unittest

#1955 Add tests for sf::Transform
  test/CMakeLists.txt
  test/Graphics/Transform.cpp
  test/TestUtilities/GraphicsUtil.cpp
  test/TestUtilities/GraphicsUtil.hpp
Labels: feature, m:sfml-graphics, s:accepted, m:unittest

#1960 Fix test and example incompatibility with ARM Macs
  examples/CMakeLists.txt
Labels: bug, s:accepted, m:unittest, m:example

#1963 Add .gitignore file
  .gitignore
Labels: feature, s:accepted, m:config

#1947 Add SFML:: namespace to targets
  cmake/Macros.cmake
  cmake/SFMLConfig.cmake.in
  cmake/SFMLConfigDependencies.cmake.in
  examples/X11/CMakeLists.txt
  examples/cocoa/CMakeLists.txt
  examples/ftp/CMakeLists.txt
  examples/island/CMakeLists.txt
  examples/joystick/CMakeLists.txt
  examples/opengl/CMakeLists.txt
  examples/shader/CMakeLists.txt
  examples/sockets/CMakeLists.txt
  examples/sound/CMakeLists.txt
  examples/sound_capture/CMakeLists.txt
  examples/tennis/CMakeLists.txt
  examples/voip/CMakeLists.txt
  examples/vulkan/CMakeLists.txt
  examples/win32/CMakeLists.txt
  examples/window/CMakeLists.txt
  src/SFML/Audio/CMakeLists.txt
  src/SFML/Graphics/CMakeLists.txt
  src/SFML/Main/CMakeLists.txt
  src/SFML/Network/CMakeLists.txt
  src/SFML/System/CMakeLists.txt
  src/SFML/Window/CMakeLists.txt
  test/CMakeLists.txt
Labels: feature, s:accepted, m:config

#1936 Add tests for sf::Clock
  test/CMakeLists.txt
  test/System/Clock.cpp
Labels: feature, s:accepted, m:unittest

#1967 Add tests for sf::ContextSettings
  test/CMakeLists.txt
  test/Window/ContextSettings.cpp
Labels: feature, s:accepted, m:unittest

#1966 Add tests for sf::BlendMode
  test/CMakeLists.txt
  test/Graphics/BlendMode.cpp
  test/TestUtilities/GraphicsUtil.cpp
  test/TestUtilities/GraphicsUtil.hpp
Labels: feature, m:sfml-graphics, s:accepted

#1971 Add support for VS 2022 to the GitHub Actions workflow
  .github/workflows/ci.yml
Labels: feature, s:accepted, m:config

#1972 Use built-in CMake project version functionality
  CMakeLists.txt
  cmake/Macros.cmake
  cmake/SFMLConfig.cmake.in
  doc/doxyfile.in
  doc/header.html.in
  tools/pkg-config/sfml-all.pc.in
  tools/pkg-config/sfml-audio.pc.in
  tools/pkg-config/sfml-graphics.pc.in
  tools/pkg-config/sfml-network.pc.in
  tools/pkg-config/sfml-system.pc.in
  tools/pkg-config/sfml-window.pc.in
  tools/windows/resource.rc.in
Labels: feature, s:accepted, m:config

#1974 Remove GCC 4 workaround
  include/SFML/Config.hpp
Labels: feature, s:accepted, m:config

#1975 Fix runtests target for multi-configuration generators
  test/CMakeLists.txt
Labels: bug, s:accepted, m:unittest

#1977 Remove unnecessary CMake version requirement
  test/CMakeLists.txt
Labels: feature, s:accepted, m:config, m:unittest

#1952 Use std::optional to remove extra sf::Rect::intersects overload
  include/SFML/Graphics/Rect.hpp
  include/SFML/Graphics/Rect.inl
  test/Graphics/Rect.cpp
Labels: feature, m:sfml-graphics, s:accepted

#1983 Don't add SFML:: namespace to external targets
  cmake/Macros.cmake
Labels: bug, s:accepted, m:config
