Repository SFML/SFML, pull requests merged in 2022-09, with the labels that each got.

#2193 Edit gitignore to ignore clion default output directory
  .gitignore
Labels: feature, s:accepted, m:config

#2195 Change Vector2 and Vector3 length function
  src/SFML/System/Vector2.cpp
  src/SFML/System/Vector3.cpp
Labels: feature, m:sfml-system, s:accepted

#2184 Use `std::size_t`
  examples/vulkan/Vulkan.cpp
  src/SFML/Audio/SoundFileReaderOgg.cpp
  src/SFML/Main/MainAndroid.cpp
  src/SFML/Main/SFMLActivity.cpp
  src/SFML/Network/Unix/SocketImpl.hpp
  src/SFML/System/Android/Activity.hpp
  src/SFML/System/Android/ResourceStream.cpp
  src/SFML/Window/Android/WindowImplAndroid.cpp
  src/SFML/Window/DRM/InputImplUDev.cpp
  src/SFML/Window/FreeBSD/JoystickImpl.cpp
  src/SFML/Window/OSX/cg_sf_conversion.hpp
  src/SFML/Window/OSX/cg_sf_conversion.mm
  src/SFML/Window/Win32/ClipboardImpl.cpp
  test/Graphics/Transform.cpp
Labels: feature, s:accepted

#2188 Treat each test case as a unique test
  CMakeLists.txt
  cmake/Macros.cmake
  test/CMakeLists.txt
Labels: feature, s:undecided, m:unittest

#2198 Time out test for public IP address
  test/Network/IpAddress.cpp
Labels: feature, m:sfml-network, s:accepted

#2212 Fix Visual Studio 2019 complaints regarding the int64_t type not being in the std namespace
  include/SFML/System/Time.hpp
Labels: bug, m:sfml-system, s:accepted, p:windows

#2216 Acknowledge latest SFML team member
  readme.md
Labels: feature, s:accepted, m:doc

#2218 Use iterator and correct string insert
  src/SFML/Network/Http.cpp
Labels: bug, m:sfml-network, s:accepted

#1834 Use modern CMake property to handle static runtime linking with MSVC
  CMakeLists.txt
  cmake/Macros.cmake
Labels: bug, s:accepted, p:windows, m:config
