Repository SFML/SFML, pull requests merged in 2022-02, with the labels that each got.

#1994 Fix findIntersection documentation
  include/SFML/Graphics/Rect.hpp
Labels: feature, m:sfml-graphics, s:accepted, m:doc

#1995 Remove VS 2017 as GitHub Actions compiler
  .github/workflows/ci.yml
Labels: feature, s:accepted, m:config

#1937 Make 'Color' constants 'constexpr' and add tests
  include/SFML/Graphics/Color.hpp
  include/SFML/Graphics/Color.inl
  src/SFML/Graphics/CMakeLists.txt
  src/SFML/Graphics/Color.cpp
  test/Graphics/Color.cpp
Labels: feature, m:sfml-graphics, m:unittest

#1997 Added support for coverage reporting.
  .github/.codecov.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/Macros.cmake
  test/Audio/Dummy.cpp
  test/CMakeLists.txt
Labels: feature, s:accepted, m:unittest

#2003 Adjust .codecov.yml to make coverage have minimal impact for now.
  .github/.codecov.yml
Labels: bug, s:accepted, m:unittest

#2002 Remove unnecessary includes from public-facing headers
  include/SFML/Audio/InputSoundFile.hpp
  include/SFML/Audio/Music.hpp
  include/SFML/Audio/Sound.hpp
  include/SFML/Graphics/Drawable.hpp
  include/SFML/Graphics/RenderTarget.hpp
  include/SFML/Graphics/RenderWindow.hpp
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/Text.hpp
  include/SFML/Graphics/Texture.hpp
  include/SFML/Network/Ftp.hpp
  include/SFML/System/Clock.hpp
  include/SFML/System/Sleep.hpp
  include/SFML/Window/Context.hpp
  include/SFML/Window/Sensor.hpp
  include/SFML/Window/Vulkan.hpp
  include/SFML/Window/Window.hpp
  src/SFML/Audio/InputSoundFile.cpp
  src/SFML/Audio/Music.cpp
  src/SFML/Audio/SoundBuffer.cpp
  src/SFML/Graphics/Font.cpp
  src/SFML/Graphics/RenderTextureImplDefault.cpp
  src/SFML/Graphics/RenderTextureImplFBO.cpp
  src/SFML/Graphics/Text.cpp
  src/SFML/Main/MainAndroid.cpp
  src/SFML/System/Clock.cpp
  src/SFML/System/Sleep.cpp
  src/SFML/System/Unix/SleepImpl.cpp
  src/SFML/System/Unix/SleepImpl.hpp
  src/SFML/System/Win32/SleepImpl.cpp
  src/SFML/System/Win32/SleepImpl.hpp
  src/SFML/Window/Unix/ClipboardImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/WindowImpl.cpp
  src/SFML/Window/iOS/EaglContext.mm
  test/System/Clock.cpp
Labels: feature, s:accepted, m:config

#2001 Fix license detection and add helpful links to external libraries and their licenses
  license.md
  readme.md
Labels: bug, s:accepted, m:doc

#1999 Turn more compile-time constants into 'constexpr' variables
  include/SFML/Graphics/Color.inl
  include/SFML/Graphics/Transform.inl
  include/SFML/System/Angle.hpp
  include/SFML/System/Angle.inl
  include/SFML/System/Time.hpp
  include/SFML/System/Time.inl
  include/SFML/System/Utf.inl
  include/SFML/Window/ContextSettings.hpp
  src/SFML/Audio/SoundFileWriterOgg.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/System/Angle.cpp
  src/SFML/System/CMakeLists.txt
  src/SFML/System/Err.cpp
  src/SFML/System/Time.cpp
  src/SFML/Window/OSX/JoystickImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Window.cpp
  src/SFML/Window/iOS/EaglContext.mm
  src/SFML/Window/iOS/SensorImpl.mm
Labels: feature, m:sfml-system, m:sfml-window, s:accepted

#2008 Fixed warnings reported by LGTM and Coverity Scan.
  examples/shader/Effect.hpp
  examples/shader/Shader.cpp
  include/SFML/Graphics/Drawable.hpp
  include/SFML/Graphics/Glyph.hpp
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/Sprite.hpp
  include/SFML/Graphics/Text.hpp
  include/SFML/Graphics/Transformable.hpp
  include/SFML/Graphics/VertexArray.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  src/SFML/Audio/Music.cpp
  src/SFML/Audio/SoundRecorder.cpp
  src/SFML/Audio/SoundStream.cpp
  src/SFML/Graphics/Font.cpp
  src/SFML/Graphics/Image.cpp
  src/SFML/Graphics/Shape.cpp
  src/SFML/Graphics/Sprite.cpp
  src/SFML/Graphics/Text.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Graphics/VertexArray.cpp
  src/SFML/Graphics/VertexBuffer.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/VulkanImplX11.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/VulkanImplWin32.cpp
  src/SFML/Window/WindowBase.cpp
  test/TestUtilities/GraphicsUtil.hpp
Labels: bug, m:sfml-window, m:sfml-graphics, m:sfml-audio, s:accepted, m:example

#2014 Add move semantics to 'sf::Packet'
  include/SFML/Network/Packet.hpp
  src/SFML/Network/Packet.cpp
Labels: feature, m:sfml-network

#2012 Simplify how tests are built
  cmake/Macros.cmake
  test/CMakeLists.txt
Labels: feature, s:accepted, m:unittest

#2015 Avoid overuse of 'std::endl'
  examples/ftp/Ftp.cpp
  examples/island/Island.cpp
  examples/sockets/TCP.cpp
  examples/sockets/UDP.cpp
  examples/sound/Sound.cpp
  examples/sound_capture/SoundCapture.cpp
  include/SFML/Audio/InputSoundFile.hpp
  src/SFML/Audio/ALCheck.cpp
  src/SFML/Audio/SoundFileWriterWav.cpp
  src/SFML/Graphics/GLCheck.cpp
  src/SFML/Graphics/GLExtensions.cpp
  src/SFML/Graphics/ImageLoader.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/RenderTextureImplFBO.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Network/Ftp.cpp
  src/SFML/Window/EGLCheck.cpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/Win32/WglContext.cpp
Labels: feature

#2016 Add move semantics to 'Font', 'Text', 'Image', and 'String'
  include/SFML/Graphics/Font.hpp
  include/SFML/Graphics/Image.hpp
  include/SFML/Graphics/Text.hpp
  include/SFML/System/String.hpp
  src/SFML/Graphics/Font.cpp
  src/SFML/Graphics/Image.cpp
  src/SFML/Graphics/Text.cpp
  src/SFML/System/String.cpp
Labels: feature, m:sfml-graphics

#2018 Remove Cygwin workaround
  CMakeLists.txt
Labels: bug, s:accepted, m:config

#2019 Use pre-increment when post-increment is not necessary
  examples/X11/gl.h
  examples/island/Island.cpp
  examples/island/stb_perlin.h
  examples/opengl/gl.h
  examples/shader/Shader.cpp
  examples/shader/resources/billboard.geom
  examples/vulkan/Vulkan.cpp
  examples/window/gl.h
  include/SFML/System/Utf.inl
  src/SFML/Audio/AlResource.cpp
  src/SFML/Audio/SoundFileReaderFlac.cpp
  src/SFML/Main/MainAndroid.cpp
  src/SFML/Network/Ftp.cpp
  src/SFML/Network/Http.cpp
  src/SFML/Network/SocketSelector.cpp
  src/SFML/Window/Android/WindowImplAndroid.cpp
  src/SFML/Window/FreeBSD/JoystickImpl.cpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/NetBSD/JoystickImpl.cpp
  src/SFML/Window/OSX/HIDJoystickManager.cpp
  src/SFML/Window/OSX/JoystickImpl.cpp
  src/SFML/Window/OSX/VideoModeImpl.cpp
  src/SFML/Window/Unix/Display.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/WglContext.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
  src/SFML/Window/iOS/SensorImpl.mm
Labels: feature

#2021 Minor include cleanup ('Window', 'RenderWindow')
  include/SFML/Window/Vulkan.hpp
  include/SFML/Window/Window.hpp
  include/SFML/Window/WindowBase.hpp
  src/SFML/Graphics/RenderWindow.cpp
  src/SFML/Window/Win32/SensorImpl.hpp
Labels: feature

#1973 Add tests for sf::Transformable
  test/CMakeLists.txt
  test/Graphics/Transformable.cpp
Labels: feature, s:accepted, m:unittest

#2022 Remove unused CMake variables
  cmake/Config.cmake
Labels: feature, s:accepted, m:config

#2024 Revert accidental filesystem conversion
  src/SFML/Audio/AudioDevice.cpp
  src/SFML/Audio/AudioDevice.hpp
Labels: bug, m:sfml-audio, s:accepted

#2025 Simplify CI workflow
  .github/workflows/ci.yml
Labels: feature, s:accepted, m:config
