Repository SFML/SFML, pull requests merged in 2022-07, with the labels that each got.

#2164 Update .gitignore for Visual Studio
  .gitignore
Labels: feature, s:accepted, m:config

#2167 Remove unnecessary CMake version checks
  CMakeLists.txt
  cmake/Macros.cmake
  src/SFML/Window/CMakeLists.txt
Labels: feature, s:accepted, m:config

#2165 Added 64bit libraries for Android
  .github/workflows/ci.yml
  extlibs/libs-android/arm64-v8a/libFLAC.a
  extlibs/libs-android/arm64-v8a/libfreetype.a
  extlibs/libs-android/arm64-v8a/libogg.a
  extlibs/libs-android/arm64-v8a/libopenal.so
  extlibs/libs-android/arm64-v8a/libvorbis.a
  extlibs/libs-android/arm64-v8a/libvorbisenc.a
  extlibs/libs-android/arm64-v8a/libvorbisfile.a
  extlibs/libs-android/armeabi-v7a/libFLAC++.a
  extlibs/libs-android/armeabi/libFLAC++.a
  extlibs/libs-android/mips/libFLAC++.a
  extlibs/libs-android/x86/libFLAC++.a
  extlibs/libs-android/x86_64/libFLAC.a
  extlibs/libs-android/x86_64/libfreetype.a
  extlibs/libs-android/x86_64/libogg.a
  extlibs/libs-android/x86_64/libopenal.so
  extlibs/libs-android/x86_64/libvorbis.a
  extlibs/libs-android/x86_64/libvorbisenc.a
  extlibs/libs-android/x86_64/libvorbisfile.a
Labels: feature, s:accepted, p:android, m:config

#2169 Remove vendored doctest header
  extlibs/headers/doctest.h
  test/CMakeLists.txt
  test/DoctestMain.cpp
  test/Graphics/BlendMode.cpp
  test/Graphics/CircleShape.cpp
  test/Graphics/Color.cpp
  test/Graphics/ConvexShape.cpp
  test/Graphics/Glyph.cpp
  test/Graphics/Image.cpp
  test/Graphics/Rect.cpp
  test/Graphics/RectangleShape.cpp
  test/Graphics/RenderStates.cpp
  test/Graphics/Shape.cpp
  test/Graphics/Transform.cpp
  test/Graphics/Transformable.cpp
  test/Graphics/Vertex.cpp
  test/Graphics/VertexArray.cpp
  test/Graphics/View.cpp
  test/Network/IpAddress.cpp
  test/Network/Packet.cpp
  test/System/Angle.cpp
  test/System/Clock.cpp
  test/System/Err.cpp
  test/System/FileInputStream.cpp
  test/System/MemoryInputStream.cpp
  test/System/Time.cpp
  test/System/Vector2.cpp
  test/System/Vector3.cpp
  test/TestUtilities/SystemUtil.cpp
  test/Window/ContextSettings.cpp
  test/Window/VideoMode.cpp
Labels: feature, s:accepted, m:unittest
