Repository SFML/SFML, pull requests merged in 2023-08, with the labels that each got.

#2632 Add iOS clang-tidy job
  .github/workflows/ci.yml
  src/SFML/Graphics/RenderTextureImplFBO.cpp
  src/SFML/Window/iOS/ClipboardImpl.mm
  src/SFML/Window/iOS/EaglContext.hpp
  src/SFML/Window/iOS/EaglContext.mm
  src/SFML/Window/iOS/SFView.mm
  src/SFML/Window/iOS/SensorImpl.mm
  src/SFML/Window/iOS/VideoModeImpl.mm
  src/SFML/Window/iOS/WindowImplUIKit.hpp
  src/SFML/Window/iOS/WindowImplUIKit.mm
Labels: feature, p:ios

#2634 Add tests for `sf::Image::loadFromFile`
  test/Graphics/Image.test.cpp
  test/Graphics/sfml-logo-big.bmp
  test/Graphics/sfml-logo-big.gif
  test/Graphics/sfml-logo-big.jpg
  test/Graphics/sfml-logo-big.png
  test/Graphics/sfml-logo-big.psd
Labels: m:sfml-graphics, m:unittest

#2639 Add tests for `sf::Sprite`
  test/Graphics/Sprite.test.cpp
Labels: feature, m:sfml-graphics, m:unittest

#2633 Test `SFML_USE_STATIC_STD_LIBS`
  .github/workflows/ci.yml
Labels: feature, p:windows, m:unittest

#2642 Use CMake Presets to Disambiguate Developer Builds from User Builds
  .github/workflows/ci.yml
  CMakePresets.json
Labels: feature, m:config

#2644 Remove `$GITHUB_WORKSPACE` where not needed
  .github/workflows/ci.yml
Labels: feature, m:config

#2647 Add CMakeUserPresets to .gitignore
  .gitignore
Labels: feature, m:config

#2655 Remove use of deprecated CMake variable
  cmake/Config.cmake
Labels: feature, m:config

#2653 Use native CMake support for detecting architecture size
  cmake/Config.cmake
Labels: feature, m:config

#2654 Remove unnecessary parentheses
  src/SFML/Graphics/Texture.cpp
  src/SFML/Window/DRM/InputImplUDev.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/Unix/VulkanImplX11.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/VulkanImplWin32.cpp
  src/SFML/Window/iOS/SFAppDelegate.mm
  src/SFML/Window/macOS/SFContext.mm
  src/SFML/Window/macOS/SFOpenGLView+keyboard.mm
  test/Graphics/Image.test.cpp
Labels: feature, m:config

#2646 Default to building static libraries
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: feature, m:config

#2657 Clean up implementation of `sf::Shader`
  src/SFML/Graphics/Shader.cpp
Labels: feature, m:sfml-graphics

#2661 Disable faulty Windows Clang job
  .github/workflows/ci.yml
Labels: bug, m:config

#2658 Enable move semantics for socket types
  include/SFML/Network/Socket.hpp
  src/SFML/Network/Socket.cpp
  test/Network/Socket.test.cpp
  test/Network/TcpListener.test.cpp
  test/Network/TcpSocket.test.cpp
  test/Network/UdpSocket.test.cpp
Labels: feature, m:sfml-network, m:unittest

#2669 Consistently use `getNativeHandle` function name
  include/SFML/Network/Socket.hpp
  include/SFML/Window/WindowBase.hpp
  include/SFML/Window/WindowHandle.hpp
  src/SFML/Network/Socket.cpp
  src/SFML/Network/SocketSelector.cpp
  src/SFML/Network/TcpListener.cpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/Network/UdpSocket.cpp
  src/SFML/Window/Android/WindowImplAndroid.cpp
  src/SFML/Window/Android/WindowImplAndroid.hpp
  src/SFML/Window/DRM/WindowImplDRM.cpp
  src/SFML/Window/DRM/WindowImplDRM.hpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/InputImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Unix/WindowImplX11.hpp
  src/SFML/Window/Win32/InputImpl.cpp
  src/SFML/Window/Win32/WglContext.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
  src/SFML/Window/Win32/WindowImplWin32.hpp
  src/SFML/Window/WindowBase.cpp
  src/SFML/Window/WindowImpl.cpp
  src/SFML/Window/WindowImpl.hpp
  src/SFML/Window/iOS/SFAppDelegate.mm
  src/SFML/Window/iOS/WindowImplUIKit.hpp
  src/SFML/Window/iOS/WindowImplUIKit.mm
  src/SFML/Window/macOS/InputImpl.mm
  src/SFML/Window/macOS/SFViewController.mm
  src/SFML/Window/macOS/SFWindowController.mm
  src/SFML/Window/macOS/WindowImplCocoa.hpp
  src/SFML/Window/macOS/WindowImplCocoa.mm
  src/SFML/Window/macOS/WindowImplDelegateProtocol.h
  test/Network/Socket.test.cpp
  test/Window/WindowBase.test.cpp
Labels: feature

#2671 fix: use non-deprecated form of UDL declaration
  include/SFML/System/Angle.hpp
  include/SFML/System/Angle.inl
Labels: bug

#2648 Remove irrelevant entries from .gitignore
  .gitignore
Labels: feature, m:config
