Repository SFML/SFML, pull requests merged in 2023-05, with the labels that each got.

#2494 Remove default `sf::Sprite` constructor
  examples/cocoa/CocoaAppDelegate.mm
  examples/shader/Shader.cpp
  examples/tennis/Tennis.cpp
  include/SFML/Graphics/RenderWindow.hpp
  include/SFML/Graphics/Sprite.hpp
  include/SFML/Graphics/Texture.hpp
  src/SFML/Graphics/Sprite.cpp
  test/install/Install.cpp
Labels: feature

#2545 Use gpg instead of gpgv to validate codecov signature
  .github/workflows/ci.yml
Labels: bug, m:config

#2519 Add `sf::WindowBase::set{Min|Max}imumSize()`
  examples/opengl/OpenGL.cpp
  include/SFML/Window/WindowBase.hpp
  src/SFML/Window/Android/WindowImplAndroid.cpp
  src/SFML/Window/Android/WindowImplAndroid.hpp
  src/SFML/Window/DRM/WindowImplDRM.cpp
  src/SFML/Window/DRM/WindowImplDRM.hpp
  src/SFML/Window/OSX/SFViewController.mm
  src/SFML/Window/OSX/SFWindowController.mm
  src/SFML/Window/OSX/WindowImplCocoa.hpp
  src/SFML/Window/OSX/WindowImplCocoa.mm
  src/SFML/Window/OSX/WindowImplDelegateProtocol.h
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Unix/WindowImplX11.hpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
  src/SFML/Window/Win32/WindowImplWin32.hpp
  src/SFML/Window/WindowBase.cpp
  src/SFML/Window/WindowImpl.cpp
  src/SFML/Window/WindowImpl.hpp
  src/SFML/Window/iOS/WindowImplUIKit.hpp
  src/SFML/Window/iOS/WindowImplUIKit.mm
  test/Window/WindowBase.test.cpp
Labels: feature, m:sfml-window

#2543 Upgrade to CMake 3.22
  CMakeLists.txt
  test/install/CMakeLists.txt
Labels: m:config

#2547 Fix broken `sf::swap` overloads
  include/SFML/Graphics/Texture.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  test/Graphics/Texture.test.cpp
  test/Graphics/VertexBuffer.test.cpp
Labels: bug, m:sfml-graphics

#2452 Switch to Catch2 v3
  .clang-format
  .github/workflows/ci.yml
  cmake/Macros.cmake
  test/CMakeLists.txt
  test/Graphics/BlendMode.test.cpp
  test/Graphics/CircleShape.test.cpp
  test/Graphics/Color.test.cpp
  test/Graphics/ConvexShape.test.cpp
  test/Graphics/Drawable.test.cpp
  test/Graphics/Glyph.test.cpp
  test/Graphics/Image.test.cpp
  test/Graphics/Rect.test.cpp
  test/Graphics/RectangleShape.test.cpp
  test/Graphics/RenderStates.test.cpp
  test/Graphics/RenderWindow.test.cpp
  test/Graphics/Shader.test.cpp
  test/Graphics/Shape.test.cpp
  test/Graphics/Texture.test.cpp
  test/Graphics/Transform.test.cpp
  test/Graphics/Transformable.test.cpp
  test/Graphics/Vertex.test.cpp
  test/Graphics/VertexArray.test.cpp
  test/Graphics/VertexBuffer.test.cpp
  test/Graphics/View.test.cpp
  test/Network/IpAddress.test.cpp
  test/Network/Packet.test.cpp
  test/System/Angle.test.cpp
  test/System/Clock.test.cpp
  test/System/Config.test.cpp
  test/System/Err.test.cpp
  test/System/FileInputStream.test.cpp
  test/System/MemoryInputStream.test.cpp
  test/System/Sleep.test.cpp
  test/System/String.test.cpp
  test/System/Time.test.cpp
  test/System/Vector2.test.cpp
  test/System/Vector3.test.cpp
  test/TestUtilities/GraphicsUtil.hpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
  test/TestUtilities/WindowUtil.cpp
  test/TestUtilities/WindowUtil.hpp
  test/Window/Context.test.cpp
  test/Window/ContextSettings.test.cpp
  test/Window/Cursor.test.cpp
  test/Window/VideoMode.test.cpp
  test/Window/Window.test.cpp
  test/Window/WindowBase.test.cpp
Labels: feature, m:unittest

#2548 Remove reference to deleted file
  .gitattributes
Labels: bug, m:config

#2549 Use C++ headers
  src/SFML/Main/SFMLActivity.cpp
Labels: bug, p:android

#2546 Manage `AAsett*` with `std::unique_ptr`
  src/SFML/System/Android/ResourceStream.cpp
  src/SFML/System/Android/ResourceStream.hpp
Labels: feature, m:sfml-system, p:android

#2537 Add `sf::Shape::getGeometricCenter()`
  include/SFML/Graphics/CircleShape.hpp
  include/SFML/Graphics/RectangleShape.hpp
  include/SFML/Graphics/Shape.hpp
  src/SFML/Graphics/CircleShape.cpp
  src/SFML/Graphics/RectangleShape.cpp
  src/SFML/Graphics/Shape.cpp
  test/Graphics/CircleShape.test.cpp
  test/Graphics/ConvexShape.test.cpp
  test/Graphics/RectangleShape.test.cpp
  test/Graphics/Shape.test.cpp
Labels: feature, m:sfml-graphics

#2557 Fix how we specify `CATCH_CONFIG_FAST_COMPILE`
  test/CMakeLists.txt
Labels: bug, m:unittest

#2560 Fix typo in log message
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Win32/WglContext.cpp
Labels: bug, p:linux

#2516 Use `std::byte`
  include/SFML/Network/Packet.hpp
  include/SFML/Network/TcpSocket.hpp
  include/SFML/Network/UdpSocket.hpp
  include/SFML/System/MemoryInputStream.hpp
  include/SFML/System/Utf.inl
  src/SFML/Audio/SoundFileReaderWav.cpp
  src/SFML/Audio/SoundFileWriterWav.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Network/Packet.cpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/System/MemoryInputStream.cpp
  src/SFML/System/Utils.hpp
Labels: feature

#2559 Fix clang-tidy-16 failures
  examples/X11/X11.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/InputImplUDev.cpp
  src/SFML/Window/DRM/VideoModeImpl.cpp
  src/SFML/Window/DRM/WindowImplDRM.cpp
  src/SFML/Window/EGLCheck.cpp
  src/SFML/Window/Unix/ClipboardImpl.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/Display.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/InputImpl.cpp
  src/SFML/Window/Unix/JoystickImpl.cpp
  src/SFML/Window/Unix/KeyboardImpl.cpp
  src/SFML/Window/Unix/VideoModeImpl.cpp
  src/SFML/Window/Unix/VulkanImplX11.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
Labels: p:linux, m:config, cleanup

#2561 Fix misspellings
  doc/searchOverrides.css
  examples/shader/resources/billboard.geom
  examples/sound/Sound.cpp
  examples/sound_capture/SoundCapture.cpp
  examples/vulkan/Vulkan.cpp
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  include/SFML/Network/Ftp.hpp
  include/SFML/Network/TcpSocket.hpp
  include/SFML/Network/UdpSocket.hpp
  include/SFML/Window/Event.hpp
  include/SFML/Window/Window.hpp
  src/SFML/Graphics/Font.cpp
  src/SFML/Main/CMakeLists.txt
  src/SFML/Network/TcpListener.cpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/Network/UdpSocket.cpp
  src/SFML/Network/Unix/SocketImpl.cpp
  src/SFML/Window/Android/WindowImplAndroid.cpp
  src/SFML/Window/CMakeLists.txt
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/OSX/HIDInputManager.hpp
  src/SFML/Window/OSX/SFOpenGLView+mouse.mm
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  test/Graphics/Shader.test.cpp
  tools/android/readme.txt
  tools/xcode/templates/SFML/SFML Compiler.xctemplate/TemplateInfo.plist.in
Labels: cleanup

#2563 Remove workaround for support old versions of Visual Studio
  src/SFML/Graphics/CMakeLists.txt
Labels: p:windows

#2562 Test for correct network ordering of packets
  test/Network/Packet.test.cpp
Labels: feature, m:sfml-network, m:unittest

#2565 Prefer named colors
  include/SFML/Graphics/Image.hpp
  include/SFML/Graphics/RenderTarget.hpp
  src/SFML/Graphics/Font.cpp
  test/Graphics/Image.test.cpp
Labels: feature, m:sfml-graphics
