Repository SFML/SFML, pull requests merged in 2023-03, with the labels that each got.

#2439 Make use of CODECOV_TOKEN in ci.yml in order to work around Github Actions API errors that occur
  .github/workflows/ci.yml
Labels: bug, s:accepted, m:config

#2433 Replace `std::rand` with `<random>`
  .clang-tidy
  examples/shader/Shader.cpp
  src/SFML/Audio/SoundFileWriterOgg.cpp
Labels: feature, s:accepted

#2440 Remove unreachable code
  src/SFML/Window/Unix/InputImpl.cpp
Labels: bug, m:sfml-audio, s:accepted

#2436 Make moving Shapes, swapping Textures and swapping VertexBuffers noexcept
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/Texture.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  src/SFML/Graphics/CMakeLists.txt
  src/SFML/Graphics/Shape.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Graphics/VertexBuffer.cpp
  test/Graphics/CircleShape.test.cpp
  test/Graphics/ConvexShape.test.cpp
  test/Graphics/RectangleShape.test.cpp
  test/Graphics/Shape.test.cpp
  test/Graphics/Texture.test.cpp
  test/Graphics/VertexBuffer.test.cpp
Labels: bug, m:sfml-graphics, s:accepted

#2441 Switch to using Documentation IP ranges in tests
  test/Network/IpAddress.test.cpp
Labels: bug, m:sfml-network, s:accepted, m:unittest

#2437 Use unity builds to speed up clang-tidy runtime
  .github/workflows/ci.yml
  test/TestUtilities/WindowUtil.hpp
Labels: feature, s:accepted, m:config

#2446 Don't automatically run tests after build
  .github/workflows/ci.yml
  test/CMakeLists.txt
Labels: bug, s:accepted, m:unittest

#2448 Remove redundant 'reset' calls in 'TransientContext` destructor
  src/SFML/Window/GlContext.cpp
Labels: feature

#2449 Use 'std::optional' in 'transientContext'
  src/SFML/Window/GlContext.cpp
Labels: feature, m:sfml-graphics, s:accepted

#2455 Manually upload coverage report instead of using codecov-action
  .github/workflows/ci.yml
Labels: bug, s:accepted, m:config

#2460 Export symbol required to use sfml-activity
  src/SFML/Main/SFMLActivity.cpp
Labels: bug, m:sfml-system, p:android

#2463 Fixed Codecov uploader being run with the wrong SHA
  .github/workflows/ci.yml
Labels: bug, m:config

#2464 Upgrade to stb_image 2.28
  extlibs/headers/stb_image/stb_image.h
Labels: bug, m:sfml-graphics

#2468 Revert from providing CODECOV_TOKEN to auto-detect
  .github/workflows/ci.yml
Labels: bug, m:config

#2456 Reduce TransientContextLock overhead if there is already a context active on the current thread
  src/SFML/Window/GlContext.cpp
Labels: bug, m:sfml-window

#2474 Replaced xvfb-run with manually starting Xvfb and running fluxbox
  .github/workflows/ci.yml
  test/CMakeLists.txt
Labels: bug, m:config

#2473 Fixed GlContext not being activated if it shares the same address as a previously destroyed GlContext.
  src/SFML/Window/CMakeLists.txt
  src/SFML/Window/GlContext.cpp
Labels: bug, m:sfml-window

#2477 Update Search in the Doxygen Documentation
  doc/CMakeLists.txt
  doc/doxyfile.in
  doc/header.html.in
  doc/searchOverrides.css
Labels: feature, m:doc

#2467 Fix clang-tidy-16 errors
  .github/workflows/ci.yml
  src/SFML/Window/OSX/SFKeyboardModifiersHelper.mm
  test/System/FileInputStream.test.cpp
Labels: m:config

#2276 sf::Texture move constructor and operator
  include/SFML/Graphics/Texture.hpp
  src/SFML/Graphics/Texture.cpp
  test/Graphics/Texture.test.cpp
Labels: feature, m:sfml-graphics

#2479 Added sf::Texture tests
  test/Graphics/Texture.test.cpp
Labels: feature, m:sfml-graphics
