Repository SFML/SFML, pull requests merged in 2023-04, with the labels that each got.

#2484 Disable stringop-overflow warning when including minimp3 since it produces false positives.
  src/SFML/Audio/SoundFileReaderMp3.cpp
Labels: bug, m:config

#2485 Feature/backmerge
  doc/CMakeLists.txt
  doc/doxyfile.in
  doc/header.html.in
  doc/searchOverrides.css
  extlibs/headers/stb_image/stb_image.h
  src/SFML/Audio/SoundFileReaderMp3.cpp
Labels: bug

#2487 Implement move semantics for `sf::Cursor`
  include/SFML/Window/Cursor.hpp
  test/Window/Cursor.test.cpp
Labels: feature, m:sfml-window

#2359 Use built-in CMake support for iOS
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/Config.cmake
  cmake/Macros.cmake
  cmake/SFMLConfigDependencies.cmake.in
  cmake/toolchains/iOS.toolchain.cmake
  examples/assets/info.plist
  src/SFML/Window/CMakeLists.txt
  test/install/CMakeLists.txt
Labels: feature, p:ios

#2481 Added sf::RenderWindow, sf::Shader and sf::Window tests.
  test/Graphics/RenderWindow.test.cpp
  test/Graphics/Shader.test.cpp
  test/Window/Window.test.cpp
Labels: feature, m:sfml-graphics

#2438 EGL pixel format selection and OpenGL version parsing fixes
  src/SFML/Graphics/RenderTextureImplFBO.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/GlContext.cpp
Labels: bug, m:sfml-window

#2488 Improve PCH by adding more commonly used headers
  src/SFML/PCH.hpp
  src/SFML/System/Win32/WindowsHeader.hpp
  src/SFML/Window/CMakeLists.txt
Labels: feature, m:config

#2480 Implement `sf::String` in terms of `std::u32string`
  include/SFML/System/String.hpp
  src/SFML/Network/Packet.cpp
  src/SFML/System/String.cpp
  src/SFML/Window/OSX/HIDInputManager.mm
  src/SFML/Window/Unix/KeySymToUnicodeMapping.cpp
  src/SFML/Window/Unix/KeySymToUnicodeMapping.hpp
  src/SFML/Window/Unix/KeyboardImpl.cpp
  test/System/String.test.cpp
Labels: feature, m:sfml-system

#2491 Use structured bindings
  examples/shader/Shader.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
Labels: feature

#2486 Remove bugprone `sf::Text` constructor
  doc/mainpage.hpp
  examples/android/app/src/main/jni/main.cpp
  examples/cocoa/CocoaAppDelegate.mm
  examples/island/Island.cpp
  examples/joystick/Joystick.cpp
  examples/opengl/OpenGL.cpp
  examples/shader/Effect.hpp
  examples/shader/Shader.cpp
  examples/tennis/Tennis.cpp
  include/SFML/Graphics/Font.hpp
  include/SFML/Graphics/RenderWindow.hpp
  include/SFML/Graphics/Text.hpp
  src/SFML/Graphics/Text.cpp
  tools/xcode/templates/SFML/SFML App.xctemplate/main.cpp
  tools/xcode/templates/SFML/SFML CLT.xctemplate/main.cpp
Labels: feature, m:sfml-graphics

#2478 Fixed OpenGL entry point loading on Windows
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/Win32/WglContext.cpp
  src/SFML/Window/Win32/WglContext.hpp
Labels: bug, m:sfml-window, p:windows

#2492 Inline `sfml_add_external`
  cmake/Macros.cmake
Labels: feature, m:config

#2498 Fixed wglGetProcAddress not providing OpenGL 1.1 functions when the context is provided by an Nvidia ICD
  src/SFML/Window/Win32/WglContext.cpp
Labels: bug, m:sfml-window

#2501 Remove unnecessary `std::string::c_str()` calls
  src/SFML/Audio/SoundFileWriterOgg.cpp
  src/SFML/Audio/SoundFileWriterWav.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Network/Ftp.cpp
Labels: feature

#2500 Clean up namespace usage
  src/SFML/Audio/Music.cpp
  src/SFML/Graphics/VertexBuffer.cpp
  src/SFML/Main/SFMLActivity.cpp
Labels: feature

#2442 Add support for using software rendering and improve CI
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/Macros.cmake
  cmake/Mesa3D.cmake
  test/Window/Context.test.cpp
Labels: feature, m:sfml-window, m:sfml-graphics, m:config

#2499 Allow for manually triggering CI
  .github/workflows/ci.yml
Labels: feature, m:config

#2512 Configure doxygen STRIP_FROM_INC_PATH option
  doc/doxyfile.in
Labels: bug, m:doc

#2510 Assorted Fixes for Testing in CI
  .github/workflows/ci.yml
Labels: bug, m:config

#2502 Add OpenGL ES jobs to ci.yml
  .github/workflows/ci.yml
Labels: feature, m:config

#2513 Add clang-tidy `bugprone-*` checks
  .clang-tidy
  include/SFML/Window/GlResource.hpp
  include/SFML/Window/WindowHandle.hpp
  src/SFML/System/Win32/WindowsHeader.hpp
  src/SFML/Window/DRM/InputImplUDev.cpp
  test/Network/Packet.test.cpp
Labels: feature, m:config

#2424 Improve test utility header compilation speed
  test/System/String.test.cpp
  test/TestUtilities/GraphicsUtil.cpp
  test/TestUtilities/GraphicsUtil.hpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
Labels: feature, m:unittest

#2514 Fixed $GITHUB_WORKSPACE backslashes being escaped by bash when passed to the sh command
  .github/workflows/ci.yml
Labels: bug, p:windows, m:config

#2523 Add clang-tidy `bugprone-incorrect-roundings` check
  .clang-tidy
  src/SFML/Graphics/RenderTarget.cpp
Labels: m:config

#2435 Fix condition for trailing bytes count in UTF-8 decoder.
  include/SFML/System/Utf.inl
  test/System/String.test.cpp
Labels: bug, m:sfml-system

#2525 fixed move semantics for sf::Cursor and added test for it.
  include/SFML/Window/Cursor.hpp
  src/SFML/Window/Cursor.cpp
  test/Window/Cursor.test.cpp
Labels: feature, m:sfml-window, m:unittest

#2534 Fix errors and warnings in templates
  tools/xcode/templates/SFML/SFML App.xctemplate/main.cpp
  tools/xcode/templates/SFML/SFML CLT.xctemplate/main.cpp
Labels: bug, m:example

#2533 Implement 'getFullscreenModes' more concisely
  src/SFML/Window/Android/VideoModeImpl.cpp
  src/SFML/Window/iOS/VideoModeImpl.mm
Labels: feature

#2531 Fix typo in 'Font.cpp'
  src/SFML/Graphics/Font.cpp
Labels: bug, m:doc

#2522 Enable clang-tidy `modernize-pass-by-value` check
  .clang-tidy
  examples/shader/Effect.hpp
  include/SFML/Graphics/Text.hpp
  include/SFML/Network/Ftp.hpp
  include/SFML/System/String.hpp
  src/SFML/Graphics/Text.cpp
  src/SFML/Network/Ftp.cpp
  src/SFML/System/String.cpp
Labels: feature, m:config

#2539 Fix typo in 'Http.hpp'
  include/SFML/Network/Http.hpp
Labels: bug, m:sfml-network

#2538 Fix macOS Window Resizing Bug
  src/SFML/Window/OSX/SFWindowController.mm
Labels: bug, m:sfml-window, p:macos
