Repository SFML/SFML, pull requests merged in 2023-01, with the labels that each got.

#2320 Empty Struct to Namespace
  include/SFML/Audio/Listener.hpp
  include/SFML/Window/Clipboard.hpp
  include/SFML/Window/Joystick.hpp
  include/SFML/Window/Keyboard.hpp
  include/SFML/Window/Mouse.hpp
  include/SFML/Window/Sensor.hpp
  include/SFML/Window/Touch.hpp
  include/SFML/Window/Vulkan.hpp
  test/install/Install.cpp
Labels: feature, s:accepted

#2310 Use in-class member initializers
  include/SFML/Audio/InputSoundFile.hpp
  include/SFML/Audio/Music.hpp
  include/SFML/Audio/Sound.hpp
  include/SFML/Audio/SoundBuffer.hpp
  include/SFML/Audio/SoundFileReader.hpp
  include/SFML/Audio/SoundRecorder.hpp
  include/SFML/Audio/SoundStream.hpp
  src/SFML/Audio/InputSoundFile.cpp
  src/SFML/Audio/Music.cpp
  src/SFML/Audio/OutputSoundFile.cpp
  src/SFML/Audio/Sound.cpp
  src/SFML/Audio/SoundBuffer.cpp
  src/SFML/Audio/SoundFileReaderFlac.cpp
  src/SFML/Audio/SoundFileReaderFlac.hpp
  src/SFML/Audio/SoundFileReaderMp3.cpp
  src/SFML/Audio/SoundFileReaderMp3.hpp
  src/SFML/Audio/SoundFileReaderOgg.cpp
  src/SFML/Audio/SoundFileReaderOgg.hpp
  src/SFML/Audio/SoundFileReaderWav.cpp
  src/SFML/Audio/SoundFileReaderWav.hpp
  src/SFML/Audio/SoundFileWriterFlac.cpp
  src/SFML/Audio/SoundFileWriterFlac.hpp
  src/SFML/Audio/SoundFileWriterOgg.cpp
  src/SFML/Audio/SoundFileWriterOgg.hpp
  src/SFML/Audio/SoundFileWriterWav.cpp
  src/SFML/Audio/SoundRecorder.cpp
  src/SFML/Audio/SoundStream.cpp
Labels: feature, m:sfml-audio, s:accepted

#2326 Simplify in-class initializer expressions
  include/SFML/Graphics/Color.hpp
  include/SFML/Graphics/Font.hpp
  include/SFML/Graphics/Glsl.inl
  include/SFML/Graphics/Glyph.hpp
  include/SFML/Graphics/Rect.hpp
  include/SFML/Graphics/RenderStates.hpp
  include/SFML/Graphics/RenderTarget.hpp
  include/SFML/Graphics/RenderWindow.hpp
  include/SFML/Graphics/Shader.hpp
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/Sprite.hpp
  include/SFML/Graphics/Text.hpp
  include/SFML/Graphics/Texture.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  include/SFML/Graphics/View.hpp
  include/SFML/Network/Http.hpp
  include/SFML/Network/Packet.hpp
  include/SFML/Network/TcpSocket.hpp
  include/SFML/System/Angle.hpp
  include/SFML/System/MemoryInputStream.hpp
  include/SFML/System/Time.hpp
  include/SFML/System/Vector2.hpp
  include/SFML/System/Vector3.hpp
  include/SFML/Window/Joystick.hpp
  include/SFML/Window/VideoMode.hpp
  src/SFML/Graphics/RenderTextureImplFBO.hpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Window/Android/WindowImplAndroid.hpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/DRMContext.hpp
  src/SFML/Window/EglContext.hpp
  src/SFML/Window/JoystickImpl.hpp
  src/SFML/Window/OSX/HIDInputManager.hpp
  src/SFML/Window/OSX/HIDJoystickManager.hpp
  src/SFML/Window/OSX/SFContext.hpp
  src/SFML/Window/Unix/ClipboardImpl.hpp
  src/SFML/Window/Unix/GlxContext.hpp
  src/SFML/Window/Unix/VulkanImplX11.cpp
  src/SFML/Window/Unix/WindowImplX11.hpp
  src/SFML/Window/Win32/CursorImpl.hpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/Win32/VulkanImplWin32.cpp
  src/SFML/Window/Win32/WglContext.hpp
  src/SFML/Window/Win32/WindowImplWin32.hpp
  src/SFML/Window/iOS/EaglContext.hpp
Labels: feature, s:accepted

#2332 Prevent constructing `sf::Text` with a temporary `sf::Font`
  include/SFML/Graphics/Text.hpp
  test/Graphics/Text.test.cpp
Labels: feature, m:sfml-graphics, s:accepted

#2335 Fix typo in error message
  src/SFML/Window/Unix/WindowImplX11.cpp
Labels: bug, m:sfml-window, s:accepted

#2337 Fix bug where clang-tidy CI job always passes
  cmake/Tidy.cmake
Labels: bug, s:accepted, m:config

#2233 Remove unnecessary static casts
  include/SFML/Graphics/Color.inl
  src/SFML/Audio/Music.cpp
  src/SFML/Graphics/Texture.cpp
  test/TestUtilities/GraphicsUtil.cpp
Labels: feature, s:accepted

#2343 Added modernize-use-nullptr check
  .clang-tidy
  examples/vulkan/Vulkan.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Window/OSX/HIDInputManager.mm
  src/SFML/Window/OSX/HIDJoystickManager.cpp
  src/SFML/Window/OSX/InputImpl.mm
  src/SFML/Window/OSX/JoystickImpl.cpp
  src/SFML/Window/OSX/NSImage+raw.mm
  src/SFML/Window/OSX/SFContext.mm
  src/SFML/Window/OSX/SFOpenGLView+keyboard.mm
  src/SFML/Window/OSX/SFOpenGLView+mouse.mm
  src/SFML/Window/OSX/SFOpenGLView.mm
  src/SFML/Window/OSX/SFViewController.mm
  src/SFML/Window/OSX/SFWindowController.mm
  src/SFML/Window/OSX/WindowImplCocoa.mm
  src/SFML/Window/Unix/ClipboardImpl.cpp
  src/SFML/Window/Unix/JoystickImpl.cpp
  src/SFML/Window/Unix/VulkanImplX11.cpp
Labels: feature, s:accepted, m:config

#2356 Analyze DRM backend
  .github/workflows/ci.yml
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/InputImplUDev.cpp
Labels: feature, m:sfml-window, s:accepted

#2238 Hide examples, tests, and documentation from projects consuming SFML via `add_subdirectory`
  CMakeLists.txt
Labels: feature, s:accepted, m:config

#2362 Added readability-container-size-empty, readability-isolate-declaration
  .clang-tidy
  examples/ftp/Ftp.cpp
  examples/vulkan/Vulkan.cpp
  examples/win32/Win32.cpp
  src/SFML/Audio/SoundFileWriterOgg.cpp
  src/SFML/Audio/SoundStream.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/InputImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
Labels: feature, s:accepted, m:config

#2364 Add clang-tidy portability checks
  .clang-tidy
Labels: feature, s:accepted, m:unittest

#2302 Enable testing types which require the presence of a display
  .github/workflows/ci.yml
  test/CMakeLists.txt
  test/Graphics/Texture.test.cpp
  test/TestUtilities/GraphicsUtil.hpp
Labels: feature, m:sfml-graphics

#2367 Added readability-qualified-auto, readability-redundant-access-specifiers
  .clang-tidy
  examples/shader/Effect.hpp
  include/SFML/Graphics/Font.hpp
  include/SFML/Graphics/Shader.hpp
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/Texture.hpp
  include/SFML/Graphics/VertexArray.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  include/SFML/Network/Packet.hpp
  include/SFML/Network/Socket.hpp
  include/SFML/System/Angle.hpp
  include/SFML/System/Time.hpp
  include/SFML/Window/Cursor.hpp
  src/SFML/Audio/SoundFileReaderFlac.hpp
  src/SFML/Audio/SoundFileReaderMp3.hpp
  src/SFML/Audio/SoundFileReaderOgg.hpp
  src/SFML/Audio/SoundFileReaderWav.hpp
  src/SFML/Audio/SoundFileWriterFlac.hpp
  src/SFML/Audio/SoundFileWriterOgg.hpp
  src/SFML/Audio/SoundFileWriterWav.hpp
  src/SFML/Graphics/Font.cpp
  src/SFML/Window/GlContext.hpp
  src/SFML/Window/OSX/HIDInputManager.hpp
  src/SFML/Window/OSX/HIDJoystickManager.hpp
  src/SFML/Window/OSX/WindowImplCocoa.hpp
  src/SFML/Window/WindowImpl.hpp
  test/System/Err.test.cpp
Labels: feature, s:accepted, m:config

#2369 Added readability-redundant-*, readability-simplify-* checks
  .clang-tidy
  examples/shader/Shader.cpp
  examples/sound_capture/SoundCapture.cpp
  src/SFML/Audio/Music.cpp
  src/SFML/Audio/SoundBuffer.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/VertexBuffer.cpp
Labels: feature, s:accepted, m:config

#2371 Streamlined readability-* clang-tidy checks
  .clang-tidy
  include/SFML/Audio/SoundSource.hpp
  src/SFML/Audio/SoundFileReaderOgg.cpp
  src/SFML/Audio/SoundSource.cpp
  src/SFML/System/Vector2.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/InputImplUDev.cpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/GlContext.hpp
  src/SFML/Window/OSX/HIDInputManager.hpp
  src/SFML/Window/OSX/HIDInputManager.mm
  src/SFML/Window/Unix/ClipboardImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/WindowImpl.cpp
  src/SFML/Window/WindowImpl.hpp
Labels: feature, s:accepted, m:config

#2330 Removed return EXIT_SUCCESS and cstdlib
  doc/mainpage.hpp
  examples/X11/X11.cpp
  examples/ftp/Ftp.cpp
  examples/island/Island.cpp
  examples/shader/Shader.cpp
  examples/sockets/Sockets.cpp
  examples/sound/Sound.cpp
  examples/sound_capture/SoundCapture.cpp
  examples/voip/VoIP.cpp
  examples/vulkan/Vulkan.cpp
  examples/win32/Win32.cpp
  tools/xcode/templates/SFML/SFML App.xctemplate/main.cpp
  tools/xcode/templates/SFML/SFML CLT.xctemplate/main.cpp
Labels: s:accepted, m:example

#2377 Replaced anonymous enums with constexpr per #2328
  include/SFML/Audio/SoundStream.hpp
  include/SFML/Graphics/RenderTarget.hpp
  include/SFML/Network/Socket.hpp
  include/SFML/Network/UdpSocket.hpp
  include/SFML/Window/Joystick.hpp
  src/SFML/Window/FreeBSD/JoystickImpl.cpp
  src/SFML/Window/NetBSD/JoystickImpl.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
Labels: feature, s:accepted

#2375 Test `sf::Drawable`
  test/Graphics/Drawable.test.cpp
Labels: feature, s:accepted, m:unittest

#2341 Fixes mostly unimportant typo in documentation of WindowBase
  include/SFML/Window/WindowBase.hpp
Labels: bug, m:sfml-window, s:accepted

#2379 Add more clang-tidy checks
  .clang-tidy
Labels: feature, s:accepted

#2381 Use Ninja in CI
  .github/workflows/ci.yml
Labels: feature, s:accepted

#2373 Replace std::strcmp by std::string_view::operator==
  examples/vulkan/Vulkan.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/Unix/VulkanImplX11.cpp
  src/SFML/Window/Win32/VulkanImplWin32.cpp
Labels: feature, s:accepted

#2384 changes this UPPER_CASE CMake function names to lower_case.
  CMakeLists.txt
Labels: bug, s:accepted, m:config

#2383 Don't install CMake on Android
  .github/workflows/ci.yml
Labels: feature, s:accepted, m:config
