Repository SFML/SFML, pull requests merged in 2024-03, with the labels that each got.

#2916 Upgrade Catch2
  test/CMakeLists.txt
Labels: feature, m:unittest

#2918 Mention CMake template in README
  readme.md
Labels: feature, m:doc

#2922 Fixed CMAKE_CXX_FLAGS being treated as a list when SFML_ENABLE_SANITIZERS is enabled
  CMakeLists.txt
Labels: bug, m:config

#2923 Remove redundant line
  .github/workflows/ci.yml
Labels: feature, m:config
