Repository SFML/SFML, pull requests merged in 2024-04, with the labels that each got.

#2924 Add more `sf::Context` tests
  test/Window/Context.test.cpp
Labels: feature, m:sfml-window, m:unittest

#2925 Return `nullptr` when `sf::Context::getFunction` is called on Windows without an active context
  include/SFML/Window/Context.hpp
  src/SFML/Window/Win32/WglContext.cpp
Labels: bug

#2926 Build Cocoa example even when not using Xcode
  examples/CMakeLists.txt
Labels: bug, m:config, m:example

#2929 Initialize all `sf::Glyph` members
  include/SFML/Graphics/Glyph.hpp
Labels: bug, m:sfml-graphics

#2932 Switch back to Codecov GitHub Action with our own token
  .github/workflows/ci.yml
Labels: feature, m:config

#2933 Update Catch2 to v3.5.4
  test/CMakeLists.txt
Labels: feature, m:unittest

#2930 Add tests for `sf::Glsl` types
  test/CMakeLists.txt
  test/Graphics/Glsl.test.cpp
Labels: feature, m:sfml-graphics, m:unittest

#2934 `constexpr`-fy `sf::priv::Vector4`
  include/SFML/Graphics/Glsl.inl
  src/SFML/Graphics/Glsl.cpp
  test/Graphics/Glsl.test.cpp
Labels: feature, m:sfml-graphics

#2935 Replaced Codecov with Coveralls.
  .github/.codecov.yml
  .github/workflows/ci.yml
  test/CMakeLists.txt
Labels: feature, m:config, m:unittest

#2937 Disable code coverage upload in forks
  .github/workflows/ci.yml
Labels: bug, m:config

#2938 Fixed coverage data not being collected for MinGW builds
  .github/workflows/ci.yml
  test/CMakeLists.txt
Labels: bug, m:config, m:unittest

#2941 Revert disabling brew update
  .github/workflows/ci.yml
Labels: feature, m:config

#2939 Use `loadIntoMemory`
  test/Audio/InputSoundFile.test.cpp
  test/TestUtilities/GraphicsUtil.cpp
  test/TestUtilities/GraphicsUtil.hpp
  test/TestUtilities/SystemUtil.cpp
  test/TestUtilities/SystemUtil.hpp
Labels: bug, m:unittest

#2944 Compile unit tests for iOS and Android
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/Macros.cmake
  test/TestUtilities/SystemUtil.cpp
Labels: feature, p:android, p:ios, m:unittest

#2950 Ensure struct data members are given an initial value
  examples/island/Island.cpp
  examples/shader/Effect.hpp
  examples/shader/Shader.cpp
  include/SFML/Audio/SoundStream.hpp
  include/SFML/Graphics/RenderTarget.hpp
  include/SFML/Graphics/StencilMode.hpp
  include/SFML/Network/Packet.hpp
  src/SFML/Network/SocketSelector.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/DRMContext.hpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/Win32/WglContext.cpp
  src/SFML/Window/WindowImpl.cpp
  src/SFML/Window/macOS/SFKeyboardModifiersHelper.mm
  test/Audio/SoundStream.test.cpp
Labels: feature

#2949 Revert change to `Drawable::draw` function signature
  examples/shader/Effect.hpp
  examples/shader/Shader.cpp
  include/SFML/Graphics/Drawable.hpp
  include/SFML/Graphics/Shape.hpp
  include/SFML/Graphics/Sprite.hpp
  include/SFML/Graphics/Text.hpp
  include/SFML/Graphics/Transformable.hpp
  include/SFML/Graphics/VertexArray.hpp
  include/SFML/Graphics/VertexBuffer.hpp
  src/SFML/Graphics/Shape.cpp
  src/SFML/Graphics/Sprite.cpp
  src/SFML/Graphics/Text.cpp
  src/SFML/Graphics/VertexArray.cpp
  src/SFML/Graphics/VertexBuffer.cpp
  test/Graphics/Drawable.test.cpp
Labels: feature, m:sfml-graphics

#2953 Silence new clang-tidy-18 checks
  .clang-tidy
Labels: feature, m:config

#2952 Use more C++17 inline variables
  include/SFML/Graphics/Shader.hpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Window/macOS/JoystickImpl.cpp
  src/SFML/Window/macOS/JoystickImpl.hpp
Labels: feature

#2954 Refactor ternary into early-returning conditionals
  examples/island/Island.cpp
Labels: feature, m:example

#2956 Address clang-tidy-18 warnings on Linux
  src/SFML/Window/Unix/Display.cpp
  src/SFML/Window/Unix/Utils.hpp
Labels: bug, p:linux

#2957 [2.6.x] [Window] Fix joystickButton being used for Joystick(Dis)Connected event
  src/SFML/Window/WindowImpl.cpp
Labels: bug, m:sfml-window

#2959 Require that variables are initialized
  .clang-tidy
  examples/sockets/Sockets.cpp
  examples/sockets/TCP.cpp
  examples/sockets/UDP.cpp
  examples/sound_capture/SoundCapture.cpp
  examples/voip/Server.cpp
  examples/voip/VoIP.cpp
  examples/vulkan/Vulkan.cpp
  include/SFML/System/Utf.inl
  src/SFML/Audio/AudioDevice.cpp
  src/SFML/Audio/MiniaudioUtils.cpp
  src/SFML/Audio/SoundRecorder.cpp
  src/SFML/Graphics/Font.cpp
  src/SFML/Graphics/RenderTextureImplFBO.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Network/Ftp.cpp
  src/SFML/Network/Http.cpp
  src/SFML/Network/Packet.cpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/Window/Android/WindowImplAndroid.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/InputImpl.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/Unix/ClipboardImpl.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/Display.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/InputImpl.cpp
  src/SFML/Window/Unix/JoystickImpl.cpp
  src/SFML/Window/Unix/VideoModeImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/Win32/WglContext.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
  src/SFML/Window/iOS/EaglContext.mm
  src/SFML/Window/iOS/SFView.mm
  src/SFML/Window/macOS/HIDInputManager.mm
  src/SFML/Window/macOS/InputImpl.mm
  src/SFML/Window/macOS/JoystickImpl.cpp
  src/SFML/Window/macOS/WindowImplCocoa.mm
  test/Network/Packet.test.cpp
Labels: feature

#2958 Unify TODO comment style for better searchability
  src/SFML/Window/Unix/SensorImpl.cpp
  src/SFML/Window/Win32/SensorImpl.cpp
  src/SFML/Window/macOS/SensorImpl.cpp
Labels: bug, m:doc

#2960 Prohibit use of malloc
  .clang-tidy
  src/SFML/Window/Unix/WindowImplX11.cpp
Labels: feature, m:config

#2961 Improve const correctness
  examples/sound_effects/SoundEffects.cpp
  src/SFML/Audio/AudioDevice.cpp
  src/SFML/Audio/SoundRecorder.cpp
  src/SFML/Audio/SoundSource.cpp
  src/SFML/Audio/SoundStream.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/Display.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/KeyboardImpl.cpp
  src/SFML/Window/Unix/VideoModeImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
Labels: feature

#2963 Use `std::optional` to express functions that may not return a value
  include/SFML/Audio/Music.hpp
  include/SFML/Audio/SoundStream.hpp
  src/SFML/Audio/Music.cpp
  src/SFML/Audio/SoundStream.cpp
Labels: feature, m:sfml-audio

#2965 Updated readme of master to point to SFML 2.6.1
  readme.md
Labels: bug, m:doc
