Repository SFML/SFML, pull requests merged in 2024-10, with the labels that each got.

#3254 Actually, don't define
  include/SFML/Audio/Export.hpp
  include/SFML/Audio/Music.hpp
  include/SFML/Config.hpp
  include/SFML/Graphics/Export.hpp
  include/SFML/Graphics/Transform.hpp
  include/SFML/Graphics/Vertex.hpp
  include/SFML/Graphics/VertexArray.hpp
  include/SFML/Network/Export.hpp
  include/SFML/Network/Ftp.hpp
  include/SFML/Network/Http.hpp
  include/SFML/Network/SocketHandle.hpp
  include/SFML/System/Export.hpp
  include/SFML/System/Vector3.hpp
  include/SFML/Window/Export.hpp
  include/SFML/Window/WindowHandle.hpp
  src/SFML/Graphics/GLCheck.hpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/Window/EGLCheck.hpp
Labels: feature, m:doc

#3258 Revert to LLVM 18 until we can upgrade to macOS 14 images
  .github/workflows/ci.yml
Labels: bug

#3257 Use explicit conversion operator instead of explicit constructor
  include/SFML/Graphics/Glsl.inl
  include/SFML/Graphics/Rect.hpp
  include/SFML/Graphics/Rect.inl
  include/SFML/System/Vector2.hpp
  include/SFML/System/Vector2.inl
  include/SFML/System/Vector3.hpp
  include/SFML/System/Vector3.inl
  test/Graphics/Glsl.test.cpp
  test/Graphics/Rect.test.cpp
  test/System/Vector2.test.cpp
  test/System/Vector3.test.cpp
Labels: feature, m:sfml-system

#3265 Remove Android CI unit testing infrastructure
  .github/workflows/ci.yml
Labels: bug, p:android, m:config

#3261 Upgrade all macOS 12 CI jobs to macOS 13
  .github/workflows/ci.yml
Labels: feature, m:config

#3264 Remove `sf::Vector2<T>::Unit[XY]`
  include/SFML/System/Vector2.hpp
  include/SFML/System/Vector2.inl
  test/System/Vector2.test.cpp
Labels: feature, m:sfml-system

#3250 Use explicit constructors when implicit construction isn't wanted
  examples/event_handling/EventHandling.cpp
  examples/sound_effects/SoundEffects.cpp
  include/SFML/Audio/InputSoundFile.hpp
  include/SFML/Audio/Music.hpp
  include/SFML/Audio/Sound.hpp
  include/SFML/Audio/SoundBuffer.hpp
  include/SFML/Graphics/Font.hpp
  include/SFML/Network/Socket.hpp
  src/SFML/Audio/SoundRecorder.cpp
  src/SFML/Audio/SoundStream.cpp
  src/SFML/Network/Ftp.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/GlxContext.hpp
  src/SFML/Window/Unix/WindowImplX11.hpp
  test/System/FileInputStream.test.cpp
Labels: feature

#3267 Use `sf::VertexArray.clear` instead of `.resize(0)`
  src/SFML/Graphics/Shape.cpp
Labels: feature, m:sfml-graphics

#3271 Remove wrong comment
  src/SFML/Graphics/Shader.cpp
Labels: feature, m:sfml-graphics

#3270 Use inherited constructors instead of constructor delegation
  include/SFML/System/Exception.hpp
  src/SFML/System/CMakeLists.txt
  src/SFML/System/Exception.cpp
Labels: feature

#3268 Merge back 2.6.x to master
  changelog.md
Labels: feature

#3269 Use initializer list instead of assigning in body
  src/SFML/System/String.cpp
Labels: feature, m:sfml-system

#3275 Use more correct iterator comparison operator
  include/SFML/System/Utf.inl
  src/SFML/Graphics/Image.cpp
Labels: feature, m:sfml-system

#3276 Remove unneeded namespace prefix for functions in implementation files
  src/SFML/Window/Joystick.cpp
  src/SFML/Window/Keyboard.cpp
  src/SFML/Window/Mouse.cpp
  src/SFML/Window/Sensor.cpp
  src/SFML/Window/Touch.cpp
  src/SFML/Window/Vulkan.cpp
Labels: feature, m:sfml-window

#3274 Remove unnecessary friend declarations
  include/SFML/System/Time.hpp
Labels: feature, m:sfml-system

#3277 Remove empty lamdba parenthesis
  src/SFML/Graphics/GLCheck.hpp
  src/SFML/Window/EGLCheck.hpp
Labels: feature

#3278 Remove specified trailing return types in lamdbas
  include/SFML/Graphics/Color.inl
Labels: feature

#3281 Stop uploading code coverage from non-pull request CI runs
  .github/workflows/ci.yml
Labels: feature, m:config

#3279 Make true and false keywords lowercase and monospaced in docs
  src/SFML/Audio/AudioDevice.hpp
  src/SFML/Audio/Sound.cpp
  src/SFML/Audio/SoundFileReaderFlac.hpp
  src/SFML/Audio/SoundFileReaderMp3.hpp
  src/SFML/Audio/SoundFileReaderOgg.hpp
  src/SFML/Audio/SoundFileReaderWav.hpp
  src/SFML/Audio/SoundFileWriterFlac.hpp
  src/SFML/Audio/SoundFileWriterOgg.hpp
  src/SFML/Audio/SoundFileWriterWav.hpp
  src/SFML/Audio/SoundStream.cpp
  src/SFML/Graphics/RenderTextureImpl.hpp
  src/SFML/Graphics/RenderTextureImplDefault.hpp
  src/SFML/Graphics/RenderTextureImplFBO.hpp
  src/SFML/Window/Android/JoystickImpl.hpp
  src/SFML/Window/Android/SensorImpl.hpp
  src/SFML/Window/Android/WindowImplAndroid.hpp
  src/SFML/Window/DRM/DRMContext.hpp
  src/SFML/Window/DRM/WindowImplDRM.hpp
  src/SFML/Window/EglContext.hpp
  src/SFML/Window/FreeBSD/JoystickImpl.hpp
  src/SFML/Window/GlContext.hpp
  src/SFML/Window/InputImpl.hpp
  src/SFML/Window/NetBSD/JoystickImpl.hpp
  src/SFML/Window/OpenBSD/JoystickImpl.hpp
  src/SFML/Window/SensorManager.hpp
  src/SFML/Window/Unix/GlxContext.hpp
  src/SFML/Window/Unix/JoystickImpl.hpp
  src/SFML/Window/Unix/SensorImpl.hpp
  src/SFML/Window/Unix/WindowImplX11.hpp
  src/SFML/Window/VulkanImpl.hpp
  src/SFML/Window/Win32/JoystickImpl.hpp
  src/SFML/Window/Win32/SensorImpl.hpp
  src/SFML/Window/Win32/WglContext.hpp
  src/SFML/Window/Win32/WindowImplWin32.hpp
  src/SFML/Window/WindowImpl.hpp
  src/SFML/Window/iOS/EaglContext.hpp
  src/SFML/Window/iOS/JoystickImpl.hpp
  src/SFML/Window/iOS/SFAppDelegate.hpp
  src/SFML/Window/iOS/SFViewController.hpp
  src/SFML/Window/iOS/SensorImpl.hpp
  src/SFML/Window/iOS/WindowImplUIKit.hpp
  src/SFML/Window/macOS/HIDInputManager.hpp
  src/SFML/Window/macOS/JoystickImpl.hpp
  src/SFML/Window/macOS/SFContext.hpp
  src/SFML/Window/macOS/SensorImpl.hpp
  src/SFML/Window/macOS/WindowImplCocoa.hpp
Labels: bug, m:doc

#3280 Use `eglCheck` macro as an expression instead of a statement
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/EglContext.cpp
Labels: bug, m:sfml-window

#3284 Add GitHub Sponsors and OpenCollective buttons
  .github/FUNDING.yml
Labels: feature, m:config

#3286 Prefer standard fixed width integers to Miniaudio's integer aliases
  src/SFML/Audio/AudioDevice.cpp
  src/SFML/Audio/CMakeLists.txt
  src/SFML/Audio/MiniaudioUtils.cpp
  src/SFML/Audio/MiniaudioUtils.hpp
  src/SFML/Audio/Sound.cpp
  src/SFML/Audio/SoundFileReaderWav.cpp
  src/SFML/Audio/SoundFileReaderWav.hpp
  src/SFML/Audio/SoundRecorder.cpp
  src/SFML/Audio/SoundStream.cpp
Labels: feature, m:sfml-audio

#3290 Remove unnecessary `static_cast`s
  src/SFML/Graphics/Font.cpp
  src/SFML/Graphics/Image.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
Labels: feature

#3288 Reduce the scope of variables
  examples/island/Island.cpp
  examples/shader/Shader.cpp
  src/SFML/Audio/AudioDevice.cpp
  src/SFML/Audio/PlaybackDevice.cpp
  src/SFML/Graphics/Image.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/VideoModeImpl.cpp
  src/SFML/Window/FreeBSD/JoystickImpl.cpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/NetBSD/JoystickImpl.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/InputImpl.cpp
  src/SFML/Window/Unix/JoystickImpl.cpp
  src/SFML/Window/Unix/VideoModeImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/ClipboardImpl.cpp
  src/SFML/Window/Win32/InputImpl.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
  src/SFML/Window/WindowImpl.cpp
  src/SFML/Window/macOS/SFContext.mm
Labels: feature

#3287 Add support to test the vulkan example on CPU
  examples/vulkan/Vulkan.cpp
Labels: feature, m:example

#3289 Upgrade to clang-format-17
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/Format.cmake
  examples/event_handling/EventHandling.cpp
  include/SFML/Audio/InputSoundFile.hpp
  include/SFML/Audio/SoundBuffer.hpp
  include/SFML/Graphics/StencilMode.hpp
  include/SFML/Network/Http.hpp
  include/SFML/Window/Event.hpp
  src/SFML/Audio/MiniaudioUtils.hpp
  src/SFML/Audio/SoundStream.cpp
  src/SFML/Graphics/Image.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Main/MainAndroid.cpp
  src/SFML/Network/Packet.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/GlContext.cpp
  src/SFML/Window/Unix/CursorImpl.cpp
  src/SFML/Window/Unix/JoystickImpl.cpp
  src/SFML/Window/Unix/KeyboardImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.hpp
  src/SFML/Window/Win32/JoystickImpl.hpp
  src/SFML/Window/Win32/WindowImplWin32.hpp
  src/SFML/Window/iOS/EaglContext.mm
  src/SFML/Window/iOS/InputImpl.mm
  src/SFML/Window/iOS/SFAppDelegate.mm
  src/SFML/Window/macOS/CursorImpl.mm
  src/SFML/Window/macOS/HIDInputManager.mm
  src/SFML/Window/macOS/InputImpl.mm
  src/SFML/Window/macOS/SFKeyboardModifiersHelper.mm
  src/SFML/Window/macOS/WindowImplCocoa.mm
Labels: feature

#3291 Disallow C-style arrays
  .clang-tidy
  examples/sockets/TCP.cpp
  examples/sockets/UDP.cpp
  examples/sound_effects/SoundEffects.cpp
  examples/vulkan/Vulkan.cpp
  include/SFML/Audio/InputSoundFile.hpp
  include/SFML/Graphics/Glsl.inl
  include/SFML/Graphics/VertexBuffer.hpp
  include/SFML/Network/TcpSocket.hpp
  include/SFML/Network/UdpSocket.hpp
  src/SFML/Audio/SoundFileReaderFlac.cpp
  src/SFML/Audio/SoundFileReaderMp3.cpp
  src/SFML/Audio/SoundFileWriterFlac.hpp
  src/SFML/Audio/SoundFileWriterWav.cpp
  src/SFML/Graphics/Glsl.cpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Network/Ftp.cpp
  src/SFML/Network/Http.cpp
  src/SFML/Network/Packet.cpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/InputImpl.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/Unix/GlxContext.cpp
  src/SFML/Window/Unix/KeyboardImpl.cpp
  src/SFML/Window/Unix/VideoModeImpl.cpp
  src/SFML/Window/Unix/WindowImplX11.cpp
  src/SFML/Window/Win32/InputImpl.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/Win32/JoystickImpl.hpp
  src/SFML/Window/Win32/WglContext.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
  src/SFML/Window/iOS/EaglContext.mm
  src/SFML/Window/macOS/HIDInputManager.mm
  src/SFML/Window/macOS/NSImage+raw.mm
  test/Graphics/Texture.test.cpp
  test/Network/Packet.test.cpp
  test/System/FileInputStream.test.cpp
  test/System/String.test.cpp
Labels: feature

#3292 Improve const correctness
  examples/island/Island.cpp
  examples/joystick/Joystick.cpp
  examples/voip/Client.cpp
  examples/voip/Server.cpp
  src/SFML/Network/Packet.cpp
  src/SFML/Network/TcpSocket.cpp
  src/SFML/Window/Android/SensorImpl.cpp
  src/SFML/Window/DRM/DRMContext.cpp
  src/SFML/Window/DRM/InputImpl.cpp
  src/SFML/Window/EglContext.cpp
  src/SFML/Window/Unix/KeyboardImpl.cpp
  src/SFML/Window/Win32/JoystickImpl.cpp
  src/SFML/Window/Win32/WindowImplWin32.cpp
Labels: feature
