Repository SFML/SFML, pull requests merged in 2024-02, with the labels that each got.

#2895 Header include clean-up and minor refactoring
  include/SFML/Audio/InputSoundFile.hpp
  include/SFML/Audio/Music.hpp
  include/SFML/Audio/SoundRecorder.hpp
  include/SFML/Audio/SoundStream.hpp
  src/SFML/Audio/InputSoundFile.cpp
  src/SFML/Graphics/GLCheck.cpp
  src/SFML/Graphics/GLCheck.hpp
  src/SFML/Graphics/RenderTarget.cpp
  src/SFML/Graphics/RenderTextureImplDefault.cpp
  src/SFML/Graphics/RenderTextureImplFBO.cpp
  src/SFML/Graphics/RenderWindow.cpp
  src/SFML/Graphics/Shader.cpp
  src/SFML/Graphics/Texture.cpp
  src/SFML/Graphics/TextureSaver.cpp
  src/SFML/Graphics/VertexBuffer.cpp
  src/SFML/Network/Ftp.cpp
Labels: feature

#2897 Self-contained '.inl' headers + minor refactoring
  include/SFML/Audio/Sound.hpp
  include/SFML/Audio/SoundBuffer.hpp
  include/SFML/Audio/SoundFileFactory.hpp
  include/SFML/Audio/SoundFileFactory.inl
  include/SFML/Graphics/Color.hpp
  include/SFML/Graphics/Color.inl
  include/SFML/Graphics/Glsl.hpp
  include/SFML/Graphics/Glsl.inl
  include/SFML/Graphics/Rect.hpp
  include/SFML/Graphics/Rect.inl
  include/SFML/Graphics/Text.hpp
  include/SFML/Graphics/Transform.hpp
  include/SFML/Graphics/Transform.inl
  include/SFML/Graphics/Vertex.hpp
  include/SFML/Graphics/Vertex.inl
  include/SFML/Network/Socket.hpp
  include/SFML/Network/TcpSocket.hpp
  include/SFML/System/Angle.hpp
  include/SFML/System/Angle.inl
  include/SFML/System/String.hpp
  include/SFML/System/String.inl
  include/SFML/System/Time.hpp
  include/SFML/System/Time.inl
  include/SFML/System/Utf.hpp
  include/SFML/System/Utf.inl
  include/SFML/System/Vector2.hpp
  include/SFML/System/Vector2.inl
  include/SFML/System/Vector3.hpp
  include/SFML/System/Vector3.inl
  src/SFML/Network/SocketImpl.hpp
  test/Graphics/Font.test.cpp
  test/Graphics/Image.test.cpp
Labels: feature

#2899 'SoundFileFactory' implementation overhaul
  examples/sound/Sound.cpp
  include/SFML/Audio/SoundFileFactory.hpp
  include/SFML/Audio/SoundFileFactory.inl
  src/SFML/Audio/SoundFileFactory.cpp
  test/Audio/SoundFileFactory.test.cpp
Labels: feature, m:sfml-audio, m:unittest, m:example

#2866 Update Catch2
  test/CMakeLists.txt
Labels: feature, m:unittest

#2903 Add static PCH CI jobs for Windows/Linux
  .github/workflows/ci.yml
Labels: feature, m:config

#2904 Replace unused '<cstring>' with '<cstdint>'
  src/SFML/Network/Win32/SocketImpl.cpp
Labels: feature, m:sfml-network

#2905 Reflect account name change in asset_licenses.md.
  examples/asset_licenses.md
Labels: feature, m:doc

#2907 Disable display tests in OpenGL ES CI jobs
  .github/workflows/ci.yml
Labels: bug, m:config, m:unittest

#2909 Fix CI deprecation warnings
  .github/workflows/ci.yml
Labels: bug, m:config

#2908 Add support for macOS arm64 builds in CI
  .github/workflows/ci.yml
Labels: feature, m:config

#2910 Fix assert not firing when only x index is out of bounds
  src/SFML/Graphics/Image.cpp
Labels: feature, m:sfml-graphics

#2912 Enable `bugprone-suspicious-include`
  .clang-tidy
Labels: feature, m:config

#2914 Use `std::{min|max}`
  src/SFML/Graphics/Text.cpp
  src/SFML/Graphics/Texture.cpp
Labels: feature

#2915 Add tests for `sf::Texture::loadFromImage`
  test/Graphics/Texture.test.cpp
Labels: feature, m:sfml-graphics, m:unittest
