Repository SFML/SFML, pull requests merged in 2025-08, with the labels that each got.

#3549 Build dependencies using unity build.
  src/SFML/Audio/CMakeLists.txt
  src/SFML/Graphics/CMakeLists.txt
  test/CMakeLists.txt
Labels: feature, m:config

#3548 docs: Add macOS Accessibility permission warning to Mouse::setPosition
  include/SFML/Window/Mouse.hpp
Labels: feature, m:doc

#3559 Prevent copy of message by moving the string
  src/SFML/Network/Ftp.cpp
Labels: bug, m:sfml-network

#3554 Add support for QOI image format
  extlibs/headers/qoi/qoi.h
  readme.md
  src/SFML/Graphics/CMakeLists.txt
  src/SFML/Graphics/Image.cpp
  test/Graphics/Image.test.cpp
  test/Graphics/sfml-logo-big.qoi
Labels: feature, m:sfml-graphics

#3564 gitignore .DS_Store files
  .gitignore
Labels: feature, m:config
