Repository SFML/SFML, pull requests merged in 2025-04, with the labels that each got.

#3366 Enable range based looping of `sf::VertexArray`
  include/SFML/Graphics/VertexArray.hpp
  src/SFML/Graphics/Shape.cpp
  src/SFML/Graphics/Text.cpp
  src/SFML/Graphics/VertexArray.cpp
  test/Graphics/VertexArray.test.cpp
Labels: feature, m:sfml-graphics

#3478 List deprecated sf::Keyboard entries & add dedicated section for sf::CoordinateType & sf::RenderStates
  migration.md
Labels: feature, m:doc

#3480 Use correct syntax for the new sf::RenderStates constructor
  migration.md
Labels: bug, m:doc

#3482 Update Catch2
  cmake/CompilerWarnings.cmake
  test/CMakeLists.txt
Labels: bug, m:unittest

#3468 Added support for making OpenGL errors fatal
  .github/workflows/ci.yml
  CMakeLists.txt
  src/SFML/Graphics/CMakeLists.txt
  src/SFML/Graphics/GLCheck.cpp
Labels: feature, m:sfml-graphics, m:config

#3491 Update glad GL headers one final time
  extlibs/headers/glad/include/glad/egl.h
  extlibs/headers/glad/include/glad/gl.h
  extlibs/headers/glad/include/glad/glx.h
  extlibs/headers/glad/include/glad/wgl.h
Labels: feature, m:sfml-window, m:sfml-graphics

#3492 Release 3.0.1
  CMakeLists.txt
  changelog.md
  cmake/SFMLConfig.cmake.in
  examples/assets/info.plist
  include/SFML/Config.hpp
Labels: feature, m:doc

#3495 Backmerge 3.0.x to master
  changelog.md
  cmake/SFMLConfig.cmake.in
  examples/assets/info.plist
  src/SFML/Main/CMakeLists.txt
Labels: feature
